import Script from 'next/script'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WebCines',
  description: 'Generated by create next app, using react',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="manifest.json" />
      </head>
      <body className={inter.className}>
        {children}
        <Script id="service-worker-script" type="module" strategy="afterInteractive">
          {`
            console.log("index.js is running");

            const registrarServiceWorker = async () => {
              if ("serviceWorker" in navigator) {
                try {
                  const registro = await navigator.serviceWorker.register("/service-worker.js", {
                    scope: "/",
                  });
                  if (registro.installing) {
                    console.log("SW instalando");
                  } else if (registro.waiting) {
                    console.log("SW instalado");
                  } else if (registro.active) {
                    console.log("SW activo");
                  }
                } catch (error) {
                  console.log("Fallo al registrar con error: ", error);
                }
              }
            };
            registrarServiceWorker();
          `}
        </Script>
      </body>
    </html>
  )
}
